# Generated by Django 5.1.4 on 2025-01-18 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finearts.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finearts.student')),
            ],
            options={
                'unique_together': {('student', 'event')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='events',
            field=models.ManyToManyField(through='finearts.StudentEvent', to='finearts.event'),
        ),
    ]
