# Generated by Django 5.1.4 on 2025-01-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0002_studentevent_student_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to St.Thomas', max_length=100)),
                ('faculty_login_url', models.URLField(default='#')),
                ('student_login_url', models.URLField(default='#')),
                ('parent_login_url', models.URLField(default='#')),
                ('footer_text', models.CharField(default='Powered by Linways Technologies Pvt. Ltd.', max_length=200)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
