# Generated by Django 5.1.4 on 2025-02-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0007_studentevent_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevent',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
